# Generated by Django 4.2.1 on 2023-05-14 04:29

from django.db import migrations, models
import history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200, validators=[history.models.validate_ip], verbose_name='ip')),
                ('access_time', models.DateTimeField(verbose_name='date accessed')),
            ],
        ),
    ]
